[package]
name = "kernel"
version.workspace = true
edition.workspace = true

[dependencies]
kernel_hal = { version = "0.1.0", path = "../kernel_hal" }
limine = "0.5.0"
log.workspace = true
object = { version = "0.1.0", path = "../object", default-features = false }
