[unstable]
bindeps = true

[target.'cfg(target_os = "none")']
rustflags = ["-Crelocation-model=static"]

[target.loongarch64-unknown-linux-musl]
linker = "rust-lld"
rustflags = ["-C", "target-feature=-lasx,-lsx"]

[alias]
k = "run --package builder --"
krun = "k run"
kdebug = "k run -s -d"
ktest = "k test"
khelp = "k help"
kclippy = "k clippy"
