[unstable]
bindeps = true

[target.'cfg(target_os = "none")']
rustflags = ["-Crelocation-model=static"]

[target.loongarch64-unknown-linux-musl]
linker = "rust-lld"
rustflags = ["-C", "target-feature=-lasx,-lsx"]

[alias]
krun = "run --package builder -- run"
ktest = "run --package builder -- test"
khelp = "run --package builder -- help"
