[package]
name = "ustd"
version.workspace = true
edition.workspace = true

[dependencies]
bitflags = "2.11.0"
errors.workspace = true
protocol = { path = "../protocol" }
spin.workspace = true
talc = "4.4.3"
