[package]
name = "ustd"
version.workspace = true
edition.workspace = true

[dependencies]
elf = { version = "0.8.0", default-features = false }
protocol = { path = "../protocol" }
vdso = { version = "0.1.0", path = "../../vdso/vdso" }
vdso_dylib = { path = "../../vdso/vdso_dylib" }
